# **Create Arrays**

In [7]:
#Create a 1D NumPy array from a Python list.
import numpy as np
array = np.array([2,5,6,7,8])
array

array([2, 5, 6, 7, 8])

In [12]:
#Create a NumPy array of zeros of size 10.
zeros_arr = np.zeros(10, dtype=int)
zeros_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
#Create a NumPy array of ones of shape (3, 4)
ones_arr = np.ones([3,4], dtype=int)
ones_arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [8]:
#Create an array with values from 5 to 50 (step = 5).
array = np.arange(5,51,5)
array

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [10]:
#Create an array of 20 random integers between 1 and 100.
array = np.random.randint(1,100,20)
array

array([38,  5, 40, 78, 81, 41, 55, 79, 50, 43, 52, 86, 53, 79, 17, 11, 63,
       80, 82,  9])