# **Basic Operations**

In [6]:
#Add 10 to every element

import numpy as np

array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(array_2d + 10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [7]:
#Multiply all elements by 2
print(array_2d*2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [8]:
#Square each element
print(array_2d**2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [10]:
#Find sum, mean, max, min
print("SUM: ", array_2d.sum())
print("MEAN: " , array_2d.mean())
print("MAX: ", array_2d.max())
print("MIN: ", array_2d.min())

SUM:  45
MEAN:  5.0
MAX:  9
MIN:  1
