# **Indexing & Slicing**

In [5]:
#Access the 5th element of a 1D array
import numpy as np

array_1d = np.array([3,5,1,2,9,7,4,6])

print(array_1d[4])

9


In [8]:
#Slice first 5 elements.
print(array_1d[:5])

[3 5 1 2 9]


In [11]:
#Extract last 3 elements
print(array_1d[-3:])

[7 4 6]


In [16]:
#Reverse a NumPy array
print(array_1d[::-1])

[6 4 7 9 2 1 5 3]


In [28]:
#Access element at row 2, column 3 from a 2D array

array_2d = np.array([ [2,4,5,7],
                      [5,6,7,9],
                      [4,7,7,6] ])
array_2d.shape

print(array_2d[2,3])

6
